// PRODUCT
export const PIZZA_ADD_DATA = "PIZZA_ADD_DATA"
export const PIZZA_GET_DATA = "PIZZA_GET_DATA"
export const PIZZA_DELETE_DATA = "PIZZA_DELETE_DATA"
export const PIZZA_UPDATE_DATA = "PIZZA_UPDATE_DATA"
export const ALL_DATA_FILTER = "ALL_DATA_FILTER"

// CATEGORY
export const CATEGORY_ADD_DATA = "CATEGORY_ADD_DATA"
export const CATEGORY_GET_DATA = "CATEGORY_GET_DATA"
export const CATEGORY_DELETE_DATA = "CATEGORY_DELETE_DATA"
export const CATEGORY_UPDATE_DATA = "CATEGORY_UPDATE_DATA"


// Authentication
export const SIGNUP_USER = 'SIGNUP_USER'
export const EMAIL_VERIFIYE = 'EMAIL_VERIFIY'
export const LOGIN_USER = 'LOGIN_USER'
export const LOGGING_USER ='LOGGING_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
export const LOGGEDOUT_USER = 'LOGGEDOUT_USER'
export const FORGOTPASSWORD_USER = 'FORGOTPASSWORD_USER'
export const GOOGLELOGIN_USER = 'GOOGLELOGIN_USER'
export const FACEBOOKLOGIN_USER="FACEBOOKLOGIN_USER"
export const PHONENUMBERLOGIN_USER = "PHONENUMBERLOGIN_USER"

// CART

export const CART_ADD_DATA = 'CART_ADD_DATA'
export const CART_GET_DATA = 'CART_GET_DATA'

// Alert
export const SET_ALERT = 'SET_ALERT'
export const RESET_ALERT = 'RESET_ALERT'